version: '3.1'

services:
  db:
    image: mariadb
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 'wahwah'
    volumes:
      - ./conf:/etc/mysql/conf.d
      - ./data:/docker-entrypoint-initdb.d
